### ISSUE TITLE
TelemetryModel class

### ISSUE THREAD

**Issue by Iyury1** [albertaloop/T_SWE_2022_2023#17]
# Summary
Use the example from Issue #13 [https://github.com/albertaloop/T_SWE_2022_2023/tree/GUI/qt-modelview/GUI/TableView-example](https://github.com/albertaloop/T_SWE_2022_2023/tree/GUI/qt-modelview/GUI/TableView-example)

We need to create a class called "TelemetryModel" as indicated in the 
[UML Class diagram](https://lucid.app/lucidchart/f6b94863-5825-48c4-a1d7-a8fc5301ab47/edit?viewport_loc=148%2C1197%2C1812%2C811%2C0_0&invitationId=inv_9ae37636-f599-47fe-80e8-7d8f7509af4d#)

The "TelemetryModel" will inherit from QAbstractTableModel and will provide data to a TableView class belonging to the "MWindowWrapper" class. The TableView example above demonstrates how to do this. "MWindowWrapper" is defined in "main2.py", and inherits from the "Ui_MainWindow" class defined in "AlbertaLoop_UI2.py".

"TelemetryModel" will contain a list of Telemetry data that will be received as telemetry packets from the "TelemetryReceiver" class. The format for the packet including the types of data are listed in a table in the Network Comms design plan located on our Google Drive:
 Albertaloop 2\3 - Electrical\2 - Software Group\1 - Design\T_SWE_PLAN - Network Communications.gdoc
 
 # Acceptance Criteria
 * [x] Initialize the TelemetryModel class with sample data representing the telemetry data we need to receive as indicated in the Network Comms design plan. Have the sample data be displayed in a TableView in the GUI.
  * [x] Update the CmdTransmitter and TelemetryReceiver classes to send the sample data over a socket using the loopback address. The TelemetryReceiver should send the data it receives to the TelemetryModel, and the TableView should automatically display the updated data.

**Comment by yashjha123** [comment]
Here's the PR resolving this issue. [#18](https://github.com/albertaloop/T_SWE_2022_2023/pull/18). Other than the TelemetryModel itself, many more changes were made in how sockets and GUI are connected. The PR lists all of them. 
A few more changes are required. Don't merge the PR before they are made. (Check #18 )
